services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./data/:/usr/wakatime/data
    env_file:
      - .env

  bot:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.bot
    ports:
      - ${BOT_PORT}:${BOT_PORT}
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env
