FROM node:22-alpine

WORKDIR /usr/wakatime

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g pnpm@latest-10

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN npm pkg delete scripts.prepare
RUN pnpm install --prod --frozen-lockfile

COPY . .

ENV NODE_NO_WARNINGS=1
CMD ["node", "--experimental-transform-types", "./src/main.ts", "api"]
