FROM ghcr.io/puppeteer/puppeteer:24.4.0

USER root
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g pnpm@latest-10

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN npm pkg delete scripts.prepare
RUN pnpm install --prod --frozen-lockfile

USER pptruser
COPY . .

ENV NODE_NO_WARNINGS=1
CMD ["node", "--experimental-transform-types", "./src/main.ts", "bot"]
