FROM node:24-alpine

WORKDIR /usr/wakatime

RUN corepack enable && corepack prepare pnpm@10.33.2 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN npm pkg delete scripts.prepare && \
    pnpm install --prod --frozen-lockfile

COPY . .

ENV NODE_NO_WARNINGS=1
CMD ["node", "--experimental-transform-types", "./src/main.ts", "api"]
