allowBuilds:
  esbuild: true
  puppeteer: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - lint-staged@17.2.0

onlyBuiltDependencies:
  - puppeteer
  - unrs-resolver
  - esbuild

savePrefix: ''
